export const POKEMON_REQUEST = 'POKEMON_REQUEST'
export const POKEMON_SUCCESS = 'POKEMON_SUCCESS'
export const POKEMON_DETAIL_SUCCESS = 'POKEMON_DETAIL_SUCCESS'
export const POKEMON_FAILED = 'POKEMON_FAILED'